### ISSUE TITLE
Be explicit in README and FirefoxPage about the call to `https://random-word-api.herokuapp.com/word`

### ISSUE THREAD

**Issue by kuolemaaa** [ahmts/Random-Username-Generator_Firefox-Extension#1]

**Comment by ahmts** [comment]
You are right about what you mentioned. I will fulfill your request shortly. Thank you for contributing to this simple project of mine. Take care and happy working.

**Comment by ahmts** [comment]
The information arrangement has been published on each platform and the relevant code has been made publicly available in the information.
